### ISSUE TITLE
[Newsletter] Coquille dans le wording dans la version anglaise

### ISSUE THREAD

**Issue by loverg-c** [eleven-labs/blog.eleven-labs.com#1098]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?
 
 Un petit point s'est glissé dans la traduction anglaise de l'optin des newsletters juste avant le lien des CGU : 
 
![image](https://github.com/eleven-labs/blog.eleven-labs.com/assets/4719382/7e528043-74c5-479c-9aa0-ab17fe9a0c95)

De plus il manque la traduction du boutton s'inscire : 

![image](https://github.com/eleven-labs/blog.eleven-labs.com/assets/4719382/b9b4a21e-f9ad-4efb-a9b6-20ec0ded5fde)

**Comment by fpasquet** [comment]
CC: @Cindyvlv

**Comment by Cindyvlv** [comment]
Good merci :)
