### ISSUE TITLE
[Newsletter] Pas de traduction des erreurs sur le formulaire 

### ISSUE THREAD

**Issue by loverg-c** [eleven-labs/blog.eleven-labs.com#1099]
BESOIN FONCTIONNEL
-------------------------------

En version anglaise, lorsque je ne remplis rien, les messages d'erreurs restent en français

![image](https://github.com/eleven-labs/blog.eleven-labs.com/assets/4719382/0839f668-12a9-46cd-beb8-10afd460d039)

**Comment by fpasquet** [comment]
CC: @Cindyvlv
