### ISSUE TITLE
[PHP] Il manque un lien vers le site dans la description et angular ne fait pas parti de php

### ISSUE THREAD

**Issue by loverg-c** [eleven-labs/blog.eleven-labs.com#1100]
BESOIN FONCTIONNEL
-------------------------------
 Sur toute les autres sections il y a un lien dans la description de la section qui renvoit vers notre expertise proposée par la boite, 
 
 Il faudrait l'ajouter pour php  
 
 (j'imagine que ça doit être ce lien : https://eleven-labs.com/dev-web/php-symfony/ )
 
![image](https://github.com/eleven-labs/blog.eleven-labs.com/assets/4719382/606d08e7-aae5-4ebf-bfb6-936ddad8193f)

**Comment by loverg-c** [comment]
D'ailleurs angular ???

**Comment by fpasquet** [comment]
CC: @Cindyvlv

**Comment by lepiaf** [comment]
pour angular @loverg-c , j'avais déjà fais un fix dans le code https://github.com/eleven-labs/blog.eleven-labs.com/pull/1096

**Comment by Cindyvlv** [comment]
C'est voulu ! Le lien vers la page que tu mentionnes est en bas de page sur le bouton "découvrir notre expertise PHP Symfony". Comme j'ai pas d'autres pages pour le moment sur le site web qui parle de Symfony, j'ai pas fait de lien dans la description :)
