### ISSUE TITLE
[Cookie consent] Pas de traduction des cookies en fonction de la langue du site

### ISSUE THREAD

**Issue by loverg-c** [eleven-labs/blog.eleven-labs.com#1102]
BESOIN FONCTIONNEL
-------------------------------
 La demande de consentement aux cookies reste en français malgré la version anglaise du site (dans la langue du navigateur peut-être ?)
 
![image](https://github.com/eleven-labs/blog.eleven-labs.com/assets/4719382/c8d5b62d-40b9-4bfe-9b62-6890406cca7b)

**Comment by fpasquet** [comment]
CC: @Cindyvlv

**Comment by Cindyvlv** [comment]
Malheureusement je ne peux rien faire pour ça. Cela demanderait d'avoir 2 plugins de cookies distincts pour avoir une version EN & FR, donc 2 facturations... :)
