### ISSUE TITLE
[Newsletters][CGU] Une version anglaise des CGU serait un plus

### ISSUE THREAD

**Issue by loverg-c** [eleven-labs/blog.eleven-labs.com#1103]
BESOIN FONCTIONNEL
-------------------------------

Sur la version anglaise, le lien vers les cgu (au niveau du formulaire de la newsletter) redirige vers la version francaise des CGU

![image](https://github.com/eleven-labs/blog.eleven-labs.com/assets/4719382/81ef4dd5-0a03-46a5-8980-364d0a349863)

![Peek 2024-04-11 16-03](https://github.com/eleven-labs/blog.eleven-labs.com/assets/4719382/8f7a4d94-a11e-490f-b701-bf1bcce97cdc)

**Comment by fpasquet** [comment]
Oui car le site "Eleven Labs" ne contient aucune autre langue que le Français et cela ne devrait pas changer.
On ne pourra rien faire à ce sujet
