### ISSUE TITLE
[UX] Traduction des noms des langues

### ISSUE THREAD

**Issue by loverg-c** [eleven-labs/blog.eleven-labs.com#1105]
Lorsque je suis en anglais je vois que lien de la version française s'appelle "French".
Idem en version française, le lien s'appelle "Anglais".

Je ne m'y connais pas assez en UX, mais pourquoi on ne laisserait pas plutôt les liens dans leur langues d'origine ? (pour que les utilisateurs anglais qui ne parlent pas français trouvent plus vite le lien vers la version anglaise)

![image](https://github.com/eleven-labs/blog.eleven-labs.com/assets/4719382/3dc34096-0837-4e29-bf9b-fc83acd4aa96)

**Comment by fpasquet** [comment]
Bien vu, fixé dans Loco ;)
