### ISSUE TITLE
[BUG] Les tableaux Markdown ne sont pas "rendered"

### ISSUE THREAD

**Issue by dimitri-fert** [eleven-labs/blog.eleven-labs.com#1113]
Les tableaux Markdown ne sont pas rendered.
Bug confirmé en prod (voir [ce billet](https://blog.eleven-labs.com/fr/explorer-la-donnee-pour-optimiser-ses-couts-d-electricite/))
![image](https://github.com/eleven-labs/blog.eleven-labs.com/assets/18677414/d28cabdd-df15-4eeb-8c53-5f4779ef868a)

---

**Given** following valid dummy embeded Markdown table in an blog article
```markdown
| Month    | Savings |
| -------- | ------- |
| January  | $250    |
| February | $80     |
| March    | $420    |
```
**When** the article is rendered 
**Then** the table is rendered following the blog template

---

#### Comportement actuel
![image](https://github.com/eleven-labs/blog.eleven-labs.com/assets/18677414/f22627f8-554f-4378-aeb2-4be2ae584d11)

#### Comportement attendu
![image](https://github.com/eleven-labs/blog.eleven-labs.com/assets/18677414/cd767f01-c96f-4bd5-8764-2fac9b75a421)

**Comment by fpasquet** [comment]
Fixed on PR https://github.com/eleven-labs/blog.eleven-labs.com/pull/1114
