### ISSUE TITLE
Le markdown n'est pas interprété dans les box admonition (raw html vs markdown)

### ISSUE THREAD

**Issue by dimitri-fert** [eleven-labs/blog.eleven-labs.com#1116]
**Etant donné** un article de blog qui contient un bloc admonition similaire à 
```html
<div class="admonition tip" markdown="1"><p class="admonition-title">Optionnel</p>
On pourra également installer la CLI `crank` qui contient des outils pour le rendering, la validation des compositions et des fonctions en local à cette adresse : 
https://releases.crossplane.io/stable/current/bin
</div>
```
**Quand** le blog est converti en html
**Alors** le texte contenu dans le div est interprété en markdown

### Comportement actuel
![image](https://github.com/eleven-labs/blog.eleven-labs.com/assets/18677414/d0dd177d-b2d2-473c-9cb3-06cb614226df)

### Comportement souhaité
L'image ci-dessous avec en plus le texte en surbrillance pour ce qui est entre les backticks (`` ` ``) 
![image](https://github.com/eleven-labs/blog.eleven-labs.com/assets/18677414/70e28a23-932a-469a-b646-f14a3166bb27)

---

Je pense que le bloc `div` dans le markdown est interprété en html brut malgré l'attribut `markdown="1"`. On voit que les backticks ne sont pas interprétés et les liens ne sont pas automatiquement générés non plus. J'ai mis un nice to have car on peut toujours compenser avec des balises <a> par exemple

**Comment by fpasquet** [comment]
Il faut simplement faire un saut de ligne entre le paragraphe et le reste du contenu mais on aurait du le spécifier dans le Readme, désoler ;)
