### ISSUE TITLE
Mettre en place un système de tag ou de catégories (PHP/Symfony, JS, Mobile, Archi, Tips) par ex)

### ISSUE THREAD

**Issue by ElevenTom** [eleven-labs/blog.eleven-labs.com#124]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?
Pour les visiteurs, pouvoir naviguer facilement à travers des articles de contenu similaires grâce à des tags

 - Comment valider ?

SPECIFICATION TECHNIQUE
------------------------------------------
*A définir par les développeurs*

**Comment by CaptainJojo** [comment]
C'est à dire avoir des pages de tags ?

**Comment by snroki** [comment]
ouep je pense qu'il veut un nuage de tag (que ça soit dans une autre page ou pas), on peut faire un _include peut-être pour ça, histoire de pouvoir l'utiliser où on veut

**Comment by ElevenTom** [comment]
Bah après je sais qu'il y a des oppositions au nuage de tags, que ça fait moche etc... 
Sinon on peut imaginer un tri approximatif ? Comme sur Medium ?
![exemple medium](https://user-images.githubusercontent.com/16896128/28362673-918d6b70-6c7d-11e7-9679-252416837156.jpg)

**Comment by VEBERArnaud** [comment]
avant de penser au display des tags/categories, il faut qu'on réflechisse a découpage en categories
