### ISSUE TITLE
Permettre le monitoring en temps réel du volume d'article traitant d'un ou plusieurs tags spécifiques, sur ou depuis une période donnée

### ISSUE THREAD

**Issue by ElevenTom** [eleven-labs/blog.eleven-labs.com#125]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?
Pour l'équipe Eleven, pouvoir savoir à n'importe quel moment combien d'articles traitent de quoi, et s'assurer d'un équilibre relatif de la nature des contenus

 - Comment valider ?

SPECIFICATION TECHNIQUE
------------------------------------------
*A définir par les développeurs*

**Comment by CaptainJojo** [comment]
je pense que c'est faisable via algolia :)

**Comment by VEBERArnaud** [comment]
avant d'avoir des stats sur les categories, il faut deja que l'on ai des categories
