### ISSUE TITLE
Mettre en place une checklist de validation d'article

### ISSUE THREAD

**Issue by ElevenTom** [eleven-labs/blog.eleven-labs.com#149]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?
S'assurer que les articles remplissent tous les prérequis avant d'être publiés
1/Le sujet est intégralement traité
2/La correction orthographique a été validée
3/L'article dispose d'une image de couverture et d'une image pour les social shares

 - Comment valider ?

SPECIFICATION TECHNIQUE
------------------------------------------

Dans le pull request template ajouter a checklist :)

**Comment by snroki** [comment]
la solution c'est quoi du coup ? Mettre cette checklist dans le README tout simplement ?

**Comment by ElevenTom** [comment]
@CaptainJojo

**Comment by VEBERArnaud** [comment]
on mettra ca dans le wiki, cf #106
