### ISSUE TITLE
Utilisation des Service Workers

### ISSUE THREAD

**Issue by ulrik59** [eleven-labs/blog.eleven-labs.com#170]
Ajout de Service Workers au site via un plugin Jekyll (https://github.com/jeremiak/jekyll-offline ?).
Cela permet d'avoir un système de cache côté front beaucoup plus efficace, de pouvoir utiliser le site en mode offline, etc...

**NECESSITE QUE LE SITE SOIT DEJA EN HTTPS OU HTTP2**

**Comment by snroki** [comment]
@CaptainJojo faut qu'on rajoute ton jeu en offline
