### ISSUE TITLE
Optimiser la fenêtre de partage sur les réseaux sociaux

### ISSUE THREAD

**Issue by ElevenTom** [eleven-labs/blog.eleven-labs.com#184]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?
L'utilisateur doit pouvoir identifier qu'il s'agit d'icônes permettant le partage sur les RS. 
 - Comment valider ?
Il faudrait idéalement rajouter la mention "share" au dessus des icônes, puis se cantonner aux partage sur : Facebook, Twitter, Linkedin, Slack et Reddit

Un peu comme ça :
![share rs](https://user-images.githubusercontent.com/16896128/28833173-d9a27d5e-76de-11e7-9714-ea1ebf9431bc.JPG)

Concrètement sur Medium c'est limpide : 
![share medium](https://user-images.githubusercontent.com/16896128/28833093-aa2bcb70-76de-11e7-83f7-b9a9d6d3ee75.JPG)

SPECIFICATION TECHNIQUE
------------------------------------------
*A définir par les développeurs*

**Comment by VEBERArnaud** [comment]
@ElevenTom & @snroki, on peut close cette issue ?

**Comment by ulrik59** [comment]
@ElevenTom @snroki ?
