### ISSUE TITLE
Actualiser le readme pour expliquer la démarche de la cover picture

### ISSUE THREAD

**Issue by MaxLf** [eleven-labs/blog.eleven-labs.com#191]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?
Dans le fichier readme qui explique comment créer un article, ajouter l'explication de la démarche pour ajouter une picture en cover (chemin du dossier, comment l'ajouter, etc...)

Penser aussi à préciser que l'astronaute doit bien vérifier en local que la picture ne rend pas le titre illisible. 

 - Comment valider ?
Le fichier readme est à jour et contient une partie Cover picture. 

SPECIFICATION TECHNIQUE
------------------------------------------
*A définir par les développeurs*

**Comment by VEBERArnaud** [comment]
a mettre dans le wiki #106
