### ISSUE TITLE
Permettre l'affichage de l'aperçu (image de cover + titre) lors du social sharing

### ISSUE THREAD

**Issue by ElevenTom** [eleven-labs/blog.eleven-labs.com#237]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?
Pouvoir partager sur les RS les articles de manière esthétique, avec une récup automatique d'un aperçu qui claque
 - Comment valider ?

SPECIFICATION TECHNIQUE
------------------------------------------
*A définir par les développeurs*

**Comment by VEBERArnaud** [comment]
un exemple ?

**Comment by ElevenTom** [comment]
Concrètement : ajouter l'image de cover lors du partage sur les réseaux sociaux
Actuellement seuls les textes sont partagés

**Comment by ulrik59** [comment]
Le souci est lié à des problèmes SEO remonté dans cette issue : https://github.com/eleven-labs/blog.eleven-labs.com/issues/317
Pour comprendre le problème, voir : https://stackoverflow.com/questions/19632323/default-website-image-for-social-sharing

**Comment by guillemcanal** [comment]
@ulrik59 @ElevenTom A mon sens rien à voir: Dans les derniers articles publiés sur le blog, les auteurs n'ont pas renseignés d'image de couverture dans leurs articles.
Exemple d'article avec image: https://blog.eleven-labs.com/fr/visualiser-l-architecture-de-vos-projets/

Dans l'article, il faut ajouter dans le frontmatter:

```yaml
image:
  path: /path/to/image.jpeg
  height: xxx
  width: xxx
```

**Comment by fpasquet** [comment]
Fixé sur la MR https://github.com/eleven-labs/blog.eleven-labs.com/pull/1123
