### ISSUE TITLE
bug - affichage des liens dans les blocs de code

### ISSUE THREAD

**Issue by qneyrat** [eleven-labs/blog.eleven-labs.com#252]
Affichage des liens dans les blocs de code en gris sur gris donc illisible.

```go
package main

import (
	grpc "google.golang.org/grpc"
)
```
`google.golang.org/grpc` apparait comme un lien et n'est pas visible

FIX:
ne pas transformer les urls en lien dans les bloc de code

**Comment by VEBERArnaud** [comment]
pour info, c'est un js qui tranforme les urls en lien

**Comment by VEBERArnaud** [comment]
j'ai poussé un peu plus loin les recherches, et c'est lié a disqus (l'outil pour les commentaires)

**Comment by VEBERArnaud** [comment]
Il faut voir avec @CaptainJojo (coucou) si il peut changer quelque chose dans les settings du compte disqus (un setting qui serait en lien avec `VigLink` ou lien sponso ou que sais-je) sinon on est bayzé.

**Comment by VEBERArnaud** [comment]
@CaptainJojo tu as eu l'occasion de vérifier du cote de disqus si il y avait une conf pour ca ?

**Comment by CaptainJojo** [comment]
je regarde
