### ISSUE TITLE
[feat] Mettre en place le multilangue

### ISSUE THREAD

**Issue by CaptainJojo** [eleven-labs/blog.eleven-labs.com#26]
# Description

Avoir la possibilité d'avoir le site en deux langues.

**Comment by CaptainJojo** [comment]
cf: https://www.sylvaindurand.fr/rendre-jekyll-multilingue/

**Comment by CaptainJojo** [comment]
ou cf: https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin

**Comment by seinhorn** [comment]
Ne faudrait-il pas ajouter des URLs alternatives par langue pour le SEO ?

ex: <link rel="alternate" hreflang="es" href="http://es.example.com/" />
cf: https://support.google.com/webmasters/answer/189077?hl=en

**Comment by ulrik59** [comment]
@CaptainJojo @eko @seinhorn À fermer ou pas ? Quand est-il du problème de SEO soulevé ci-dessus ? J'ai essayé de faire une PR mais ça s'est avéré beaucoup plus complexe que ce que je pensais...
