### ISSUE TITLE
Question: how does enabling GitHub public_repo API token not a security risk?

### ISSUE THREAD

**Issue by luzpaz** [eleven-labs/blog.eleven-labs.com#263]
Sorry for posting here, I read your [blog post](https://blog.eleven-labs.com/en/how-to-check-the-spelling-of-your-docs-from-travis-ci/) and got to the part of enabling `public_repo` token. Reading more about the scope of this token in the [GitHub API docs](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-scopes-for-oauth-apps/) it says:

>Grants read/write access to code, commit statuses, collaborators, and deployment statuses for public repositories and organizations. Also required for starring public repositories.

That's a lot of power. Now I know it's hidden via TravisCI but is that enough?

**Comment by ulrik59** [comment]
@ch3ric please respond or close.
