### ISSUE TITLE
[feat][Bonus] Faire une PWA

### ISSUE THREAD

**Issue by CaptainJojo** [eleven-labs/blog.eleven-labs.com#27]
# Description

Faire que le blog soit une PWA

**Comment by ulrik59** [comment]
Avec les dernières amélioration, le site est maintenant une PWA.
Test réalisé avec Google LightHouse : 
![capture du 2017-11-09 10-44-03](https://user-images.githubusercontent.com/6003644/32598960-5bc481ec-c53b-11e7-92f9-f199709a1ab8.png)
