### ISSUE TITLE
Version EN : traduire le titre du blog et le logo

### ISSUE THREAD

**Issue by seinhorn** [eleven-labs/blog.eleven-labs.com#312]
BESOIN FONCTIONNEL
-------------------------------
 - traduire le titre du blog et le logo => "Eleven Labs Blog"

SPECIFICATION TECHNIQUE
------------------------------------------
- [x] créer un logo "Eleven Labs blog" pour le header
- [x] créer une image "Eleven Labs blog" pour la homepage
- [ ] modifier le <title> et le h1 :  "Eleven Labs blog"

**Comment by VEBERArnaud** [comment]
@seinhorn je vois que cette issue est linké dans une PR mergé, on peut close cette issue ou il reste du travail dessus ?

**Comment by seinhorn** [comment]
@VEBERArnaud : Issue OK sauf modifier le <title> et le h1 : "Eleven Labs blog" (créer une issue à part ?)
