### ISSUE TITLE
Avoir un <h1> unique sur les pages du site

### ISSUE THREAD

**Issue by seinhorn** [eleven-labs/blog.eleven-labs.com#313]
BESOIN FONCTIONNEL
-------------------------------
 - Avoir un h1 unique sur les pages du site (pour le SEO)

SPECIFICATION TECHNIQUE
------------------------------------------
- supprimer le h1 sur le logo du header du blog
- sur la homepage, mettre le h1 sur le logo "banner" / titre sur fond jaune avec le cosmonaute (comme sur les articles)

**Comment by VEBERArnaud** [comment]
@seinhorn je vois que cette issue est linké dans une PR mergé, on peut close cette issue ou il reste du travail dessus ?

**Comment by seinhorn** [comment]
@VEBERArnaud : Issue terminée !
