### ISSUE TITLE
Améliorer la lisibilité des titres des articles

### ISSUE THREAD

**Issue by seinhorn** [eleven-labs/blog.eleven-labs.com#314]
BESOIN FONCTIONNEL
-------------------------------
- Améliorer la lisibilité des titres des articles (texte blanc sur image de fond)
- Version mobile : modifier l'apparence des titres

![titre-blog-apparence](https://user-images.githubusercontent.com/1998524/32616275-311a8d6a-c572-11e7-881a-bd598cd5e009.png)

![blog-capture](https://user-images.githubusercontent.com/1998524/32615180-5b2acbfe-c56f-11e7-9d4e-b1d577fefda8.png)

SPECIFICATION TECHNIQUE
------------------------------------------
- ajouter un "bandeau noir avec opacité" par dessus la couverture de l'article
- Version mobile : élargir la zone du titre

**Comment by VEBERArnaud** [comment]
@seinhorn je vois que cette issue est linké dans une PR mergé, on peut close cette issue ou il reste du travail dessus ?

**Comment by seinhorn** [comment]
@VEBERArnaud : Issue terminée !
