### ISSUE TITLE
Modifier l'apparence des liens sur la page auteur

### ISSUE THREAD

**Issue by seinhorn** [eleven-labs/blog.eleven-labs.com#315]
BESOIN FONCTIONNEL
-------------------------------
- modifier l'apparence des liens sur les icônes de réseaux sociaux

![author-header2](https://user-images.githubusercontent.com/1998524/32615643-88ad5992-c570-11e7-8cc0-b4096bffb112.png)

**Comment by VEBERArnaud** [comment]
@seinhorn je vois que cette issue est linké dans une PR mergé, on peut close cette issue ou il reste du travail dessus ?

**Comment by seinhorn** [comment]
@VEBERArnaud : Issue terminée !
