### ISSUE TITLE
Améliorer la visibilité du footer

### ISSUE THREAD

**Issue by seinhorn** [eleven-labs/blog.eleven-labs.com#316]
BESOIN FONCTIONNEL
-------------------------------
- la zone du footer est peu lisible ("Nous contacter" / "To infinity and beyond !")
- Version mobile : le footer est masqué par les boutons de partage

![footer](https://user-images.githubusercontent.com/1998524/32616074-bdfc71d6-c571-11e7-90fb-35bf2f36a8b0.png)

SPECIFICATION TECHNIQUE
------------------------------------------
- augmenter la taille de la police
- Version mobile : ajouter une marge

**Comment by VEBERArnaud** [comment]
@seinhorn je vois que cette issue est linké dans une PR mergé, on peut close cette issue ou il reste du travail dessus ?

**Comment by seinhorn** [comment]
@VEBERArnaud : Issue terminée !
