### ISSUE TITLE
Modifier le look des différents niveaux de titre des articles

### ISSUE THREAD

**Issue by seinhorn** [eleven-labs/blog.eleven-labs.com#318]
Proposition graphique pour les titres h2 et h3 
- h2 : titre noir sur fond jaune (garder le décalage à gauche)
        > appliquer le "jaune de la charte Eleven Labs" (#fde300 à la place de #fbe300)
- h3 : titre noir sur fond gris

![capture-post](https://user-images.githubusercontent.com/1998524/32617600-a92b3252-c575-11e7-8f03-c27db248d483.png)

**Comment by VEBERArnaud** [comment]
@seinhorn je vois que cette issue est linké dans une PR mergé, on peut close cette issue ou il reste du travail dessus ?

**Comment by seinhorn** [comment]
@VEBERArnaud : Issue terminée !
