### ISSUE TITLE
Améliorer les performances du blog

### ISSUE THREAD

**Issue by seinhorn** [eleven-labs/blog.eleven-labs.com#324]
- Améliorer la version mobile de la homepage

![perf1](https://user-images.githubusercontent.com/1998524/32653106-ec511ac4-c606-11e7-9a83-a1c339db17aa.png)

- Passer en revue les articles dont les performances sont faibles
   > analyser les performances
   > proposer des améliorations

![perf2](https://user-images.githubusercontent.com/1998524/32653233-6d809868-c607-11e7-984a-6a1ca16a1652.png)

![perf3](https://user-images.githubusercontent.com/1998524/32653234-6fd08128-c607-11e7-8c37-1ab7e07c4e1b.png)

**Comment by ulrik59** [comment]
@seinhorn Suite aux optimisations des images, les scores ont bien augmentés. Il reste principalement à corriger les soucis de cache des fichiers statiques et à rendre le chargement des fichiers CSS non bloquant.

**Comment by ulrik59** [comment]
@seinhorn 
![capture du 2018-01-23 14-15-26](https://user-images.githubusercontent.com/6003644/35277848-5a54045c-0048-11e8-8b05-1012a9fd9843.png)
![capture du 2018-01-23 14-15-51](https://user-images.githubusercontent.com/6003644/35277864-66935fce-0048-11e8-9453-f13bb264d0c6.png)

**Comment by ulrik59** [comment]
@seinhorn Tu peux fermer ou pas cet issue ?
![capture du 2018-03-15 15-44-28](https://user-images.githubusercontent.com/6003644/37470713-6e18f4f0-2868-11e8-8c37-4365c78dd126.png)
![capture du 2018-03-15 15-44-43](https://user-images.githubusercontent.com/6003644/37470714-6e340a38-2868-11e8-8a9b-abb731c74f39.png)
![capture du 2018-03-15 15-48-02](https://user-images.githubusercontent.com/6003644/37470715-6e4d7e96-2868-11e8-82c4-a5ca54beb197.png)
![capture du 2018-03-15 15-48-32](https://user-images.githubusercontent.com/6003644/37470716-6e6a73d4-2868-11e8-9cf7-eb64aeae2964.png)

**Comment by Leones007** [comment]
Для чего этот сайт

**Comment by ulrik59** [comment]
почему бы и нет?
