### ISSUE TITLE
[Header] Ouvrir les liens exterieurs en target="_blank" 

### ISSUE THREAD

**Issue by Pouzor** [eleven-labs/blog.eleven-labs.com#333]
BESOIN FONCTIONNEL
-------------------------------
Dans le header, ouvrir les liens extérieurs (tweeter, github, site ect...) dans un nouvel onglet.

SEO, confort de lecture ect...

**Comment by VEBERArnaud** [comment]
je pense qu'il faut laisser le choix a l'utilisateur

**Comment by ulrik59** [comment]
Moi je suis d'accord tout au contraire, cela fait partie des bases d'ergonomie pour moi. Laissons trancher @ElevenTom .

**Comment by alex-ception** [comment]
Dans l'absolu je suis pour, mais les commentaires précédents sont plutôt pertinents. La molette, le ctrl+clic etc...

**Comment by guillemcanal** [comment]
👎 Je vote contre (on a déjà le clic molette et l'appuie long ouvrir dans un nouvel onglet sur mobile). Laissons le choix à l'utilisateur.

**Comment by Pouzor** [comment]
En fait a minima je prenais juste les liens dans le header mais on peut peut etre pousser pour tout les liens...
