### ISSUE TITLE
Aucun header Cache-Control

### ISSUE THREAD

**Issue by ulrik59** [eleven-labs/blog.eleven-labs.com#338]
Aucune requête venant du serveur ne possède de header `Cache-Control`.
Il faudrait que les fichiers dit statique (js, css, fonts, image...) soit au moins caché.
Voir diagnostic sur : http://yellowlab.tools/result/evjtzvhzje
![capture du 2017-11-16 18-08-27](https://user-images.githubusercontent.com/6003644/32905051-2bc36350-caf9-11e7-8e9f-eebcfd376400.png)

**Comment by VEBERArnaud** [comment]
je vais m'en occuper

**Comment by ulrik59** [comment]
Il faudrait un header "Cache-Control" sur tout (image, css, js, font, page...). Le temps de cache est à définir mais c'est minimum 1h (voire une journée) sur tout excepté le fichier `sw.js` qui doit explicitement avoir la valeur "no-cache".
Exemple d'une partie d'une conf Apache concernant ce dernier fichier : 
```apache
<IfModule mod_headers.c>
  # Do not cache sw.js, required for offline-first updates.
  <FilesMatch "sw\.js$">
    Header set Cache-Control "private, no-cache, no-store, proxy-revalidate, no-transform"
    Header set Pragma "no-cache"
  </FilesMatch>
</IfModule>
```

**Comment by VEBERArnaud** [comment]
on utilise du stockage static s3 avec un cdn cloudfront, on a pas acces a la conf du serveur web

**Comment by ulrik59** [comment]
Il y a possibilité de le faire même si ça parait inutilement compliqué :/ : 
https://serverfault.com/questions/770302/no-cache-control-header-for-files-from-aws-cloudfront-with-s3-origin
https://stackoverflow.com/questions/21605501/how-to-set-expires-header-to-all-images-in-a-bucket-in-amazon-s3/30225271#30225271
