### ISSUE TITLE
Absence des noms d'auteurs lors des recherches

### ISSUE THREAD

**Issue by ElevenTom** [eleven-labs/blog.eleven-labs.com#371]
Quand on fait une recherche, les articles qui apparaissent en résultat ne contiennent que le titre, l'abstract, et la date, mais l'auteur n’apparaît pas. Pas possible de faire une recherche par auteur, donc.
![champ auteur manquant](https://user-images.githubusercontent.com/16896128/33760864-92bc7b68-dc07-11e7-8980-94e8d4ec80db.png)

**Comment by VEBERArnaud** [comment]
pourquoi tu voudrait faire une recherche par auteur, sachant qu'il existe des pages auteurs ?

**Comment by ElevenTom** [comment]
Bah par exemple je cherchais un article de Chéric. Sauf que ça fait un moment qu'il a pas publié. Je t'avoue que la flemme de remonter les pages une à une, du coup recherche !

**Comment by ElevenTom** [comment]
Tu peux accéder au pages auteurs oui, mais que de ceux qui ont publié il y a pas longtemps. Après faut faire de la spéléo.

**Comment by VEBERArnaud** [comment]
Je ne pense pas que ce soit un cas d'utilisation courant.
Mais admettons que ce soit un vrai besoin, ajouter le nom de l'auteur dans l'affichage des résultats de recherche ne changera pas la liste de résultats pour une recherche...

La recherche est faite sur le contenu de l'article, pas sur son affichage.

**Comment by ulrik59** [comment]
On pourrait faire une page "auteurs" qui liste ces derniers. Ça réglerait le souci, non ?

**Comment by VEBERArnaud** [comment]
Ca me paraît être une bonne solution, mais ça implique de trouver un endroit où mettre le(s) lien(s) vers cette page

**Comment by MaxLf** [comment]
Personnellement ça me parait plus long et moins intuitif comme manip de devoir aller sur une page des auteurs pour retrouver un auteur. 

C'est pas envisageable l'option proposé par Tom qui serait que le nom de des auteurs soit intégré dans le contenu qui est recherché via le champ de recherche ?

**Comment by VEBERArnaud** [comment]
C’est certainement faisable mais ça sera beaucoup moins efficace

**Comment by MaxLf** [comment]
Ah, c'est ce qui me paraissait le plus efficace justement ahah. J'arrive, je tape "Arnaud" dans la barre de recherche et tous tes articles (ou ceux qui mentionnent Arnaud of course) apparaissent.

Pourquoi ça l'est moins selon toi ?

**Comment by VEBERArnaud** [comment]
Parce que la recherche “plein texte” se base sur l’ensemble du contenu sans tenir compte du but. 

Qu’il y ai écrit arnaud dans le contenu ou que Arnaud soit l’auteur ne fera pas de différence. 

Autre cas ou c’est embêtant, les prénoms multi auteurs, prenons par exemple Alexandre, les articles de tous les alexandre vont ressortir.

**Comment by VEBERArnaud** [comment]
Chaque élément doit avoir une fonction définie si tu ne veut pas embrouiller les utilisateurs

De mon point de vue la recherche, sert à rechercher dans les datas, pas les metadatas.

**Comment by ElevenTom** [comment]
Oui je trouve ça cool Une page avec tous les auteurs

**Comment by MaxLf** [comment]
Je comprends l'argument en effet. J'avoue que moi le fait de sortir tous les Alexandre quand je recherche "Alexandre" (ou juste tous les articles qui contiennent le mot "Alexandre") est tout à fait normal et c'est justement à l'utilisateur d'être plus précis s'il veut que la recherche soit plus précise (par exemple en mettant aussi un nom de famille, etc...)

Après cela n'engage évidemment que moi, j'ai moins le point de vue tech en effet, ça se base plus sur l'expérience des nombreuses recherches que j'ai du faire côté études ou côté pro.
