### ISSUE TITLE
Afficher Workshops à venir + possibilité de s'inscrire ou de commander workshop

### ISSUE THREAD

**Issue by ElevenTom** [eleven-labs/blog.eleven-labs.com#43]

**Comment by CaptainJojo** [comment]
l'idée c'est d'avoir une page Workshop ?

**Comment by ElevenTom** [comment]
Une page ou un espèce de widget. Le but c'est de permettre aux gens de suivre les workshops à venir pour qu'ils puissent y participer.

**Comment by VEBERArnaud** [comment]
Je ne pense pas que le blog soit le bon media pour ce besoin

**Comment by ulrik59** [comment]
@ElevenTom Codelabs semble plus indiqué pour ce besoin. À fermer ?
