### ISSUE TITLE
Permettre soumission d'articles aux extérieurs via un call-to-action

### ISSUE THREAD

**Issue by ElevenTom** [eleven-labs/blog.eleven-labs.com#45]

**Comment by VEBERArnaud** [comment]
c'est déjà le cas, suffit de faire une PR :smirk:

**Comment by ElevenTom** [comment]
C'est techniquement possible, mais j'aurais bien voulu un call-to-action.
Que ce soit une vraie invitation et pas seulement une possibilité.
"Vous voulez soumettre votre propre article ? Cliquez ici" Un truc dans le genre.

**Comment by Pouzor** [comment]
On peut toujours faire un how to

**Comment by CaptainJojo** [comment]
le call to action me parait pas mal mais où ?

**Comment by VEBERArnaud** [comment]
on pourrait par exemple faire un truc comme sur la doc symfony (bouton `edit this page`)

**Comment by VEBERArnaud** [comment]
j'ai lu en travers mais il y a des chances pour que ca corresponde a ce que l'on veut faire http://eeemil.com/guides/2015/02/11/creating-an-edit-this-post-on-github-button.html

**Comment by VEBERArnaud** [comment]
Est-il possible d'avoir un retour sur les solutions proposées ?
