### ISSUE TITLE
Ajouter les tutos Codelabs sur les pages auteurs

### ISSUE THREAD

**Issue by MaxLf** [eleven-labs/blog.eleven-labs.com#459]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ? 
Les pages auteurs de Codelabs sont enfait celles du blog. Quand on arrive sur celles-ci, dans la catégorie "Du même auteur" il serait intéressant d'avoir également la liste des tutos en plus de la liste des articles.

 - Comment valider ?
Sur la page auteur d'un auteur, dans la catégorie "Du même auteur" je peux voir la liste des articles ET la liste des tutos, avec un tag avant chaque titre du type
[Article] Blablabla
[Article] Blablabla
[Tuto] Blablabla

Pour les tutos, rajouter la petite flèche symbolisant qu'on se dirige vers un site externe. 
![image](https://user-images.githubusercontent.com/12557493/38131173-5bf4f162-3406-11e8-9f39-c12f73b2cc57.png)

SPECIFICATION TECHNIQUE
------------------------------------------
*A définir par les développeurs*

**Comment by ulrik59** [comment]
Mmmh, je suis pas sûr que cela soit pertinent, sachant que ce ne sont pas les même sites. Je trouve ça confusant pour l'utilisateur. De plus techniquement, c'est plus que galère, il faudrait les ajouter à la main à chaque fois...

**Comment by fpasquet** [comment]
Codelabs migré sur le blog, donc feature OK
