### ISSUE TITLE
Penser le Download des Livres Blancs

### ISSUE THREAD

**Issue by ElevenTom** [eleven-labs/blog.eleven-labs.com#46]

**Comment by VEBERArnaud** [comment]
un ajout dans le dossier des assets devrait être suffisant pour permettre le download de PDFs

**Comment by Pouzor** [comment]
Sinon, tu vois ca comment niveau front ? Un lien vers une page ou il y a tout les livres blancs ? Fans le header ? @ElevenTom

**Comment by CaptainJojo** [comment]
normalement c'est très simple, apres on est encore entrain deréfléchir à la présentation des livres blanc

**Comment by VEBERArnaud** [comment]
Je close cette issue, on re-ouvrira le jour ou la problématique sera réelle
