### ISSUE TITLE
Utilisation de Netlify

### ISSUE THREAD

**Issue by flemzord** [eleven-labs/blog.eleven-labs.com#468]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?
A voir une preview de chaque PR lors de la création / update
https://www.netlify.com 

 - Comment valider ?
Il peut être activer dans un premier temps uniquement pour faire la prévisualisation des PR sans remplacer la PROD.

SPECIFICATION TECHNIQUE
------------------------------------------
- Configuration de Netlify
- Validation de Netlify
- Migration DNS vers les serveurs de Netlify
- Arrêt de l'utilisation de AWS S3 / Cloudfront

**Comment by flemzord** [comment]
@VEBERArnaud Je te laisse regarder la solution :)

**Comment by Vubs** [comment]
Ça m'intéresse de savoir pourquoi tu veux faire ça @flemzord  ! Tu veux plus utiliser AWS ? C'est plus perf Netlify ? J'ai utilisé ça avant hier je me demandais si c'était pas mieux de stocker chez amazon

**Comment by cbm-mmaireaux** [comment]
@Vubs Plus simple, pas de gestion, automatique. 
Les PR se retrouve automatique avec le liens pour pouvoir tester.

Et gratuit pour les projets Open Source comme le blog :)

**Comment by Vubs** [comment]
Niveau lien pour pouvoir tester on à déjà ça non ? Le "view deployment" 
Ok bah je vais approfondir, mais c'est grave cher d'ajouter des collaborateur sur le projet du coup non ? J'ai voulu ajouter quelqu'un dans une "team" ça m'a dit direct d'entrée de jeu c'est 45 ou 49$ ^^' 
Merci pour les infos @cbm-mmaireaux  :)

**Comment by Pouzor** [comment]
@Vubs 6 Arp 2018 t'es un peu a la bourre :D

**Comment by Vubs** [comment]
@Pouzor j'ai vu APRES avoir posté le premier message mdr, c'est un truc de fou t'es un detecteur de trucs :old: :')
