### ISSUE TITLE
Handle no picture in author page

### ISSUE THREAD

**Issue by Pouzor** [eleven-labs/blog.eleven-labs.com#633]
Remove the block if no picture on the author page

![image](https://user-images.githubusercontent.com/961315/55546853-66d60880-56d0-11e9-83a0-222896452e5f.png)

**Comment by Vubs** [comment]
J'ai essayé un truc, https://github.com/eleven-labs/blog.eleven-labs.com/pull/637 ça fonctionne, je sais pas trop ce que ça vaut niveau opti mais je voyais rien de mieux, je suis preneur de conseils @Pouzor

**Comment by Pouzor** [comment]
Pas ouf comme solution.
On pourrait essayer de faire ca en JS un peu comme dans cet exemple : 
https://css-tricks.com/snippets/jquery/better-broken-image-handling/

**Comment by Vubs** [comment]
ça marche je savais pas si je pouvais essayer un truc en JS, j'essai ça :)

**Comment by Vubs** [comment]
Conclusion : 
Le JS est load trop tard, je n'ai pas réussi a catch l'event, j'ai trouvé une autre solution, en virant la div autour de l'image qui ne sert à rien, et en fixant le onerror directement sur l'image.

**Comment by Pouzor** [comment]
appears to be corrected
