### ISSUE TITLE
No author name on the first article

### ISSUE THREAD

**Issue by Pouzor** [eleven-labs/blog.eleven-labs.com#636]
<img width="1083" alt="Capture d’écran 2019-04-04 à 12 00 40" src="https://user-images.githubusercontent.com/961315/55547299-4d818c00-56d1-11e9-8582-65c1931f7b04.png">

**Comment by Vubs** [comment]
Je crois que ça va se résoudre avec cette PR https://github.com/eleven-labs/blog.eleven-labs.com/pull/632 @Pouzor

**Comment by flemzord** [comment]
Fix !
