### ISSUE TITLE
[Bug] "Invalid date" pour les articles retournés par la recherche

### ISSUE THREAD

**Issue by dimitri-fert** [eleven-labs/blog.eleven-labs.com#707]
COMPORTEMENT
-------------------------------
`Invalid date` est affiché sur tous les articles de blogs retournés par la fonctionnalité de recherche au lieu de la date de l'article en question. Le gif ci-dessous montre que les dates s'affichent correctement avant d'utiliser la fonction de recherche

![bug_date_blog](https://user-images.githubusercontent.com/18677414/67678465-93a88080-f97e-11e9-8b5a-c564d212b2c3.gif)

Les images ci-dessous montrent le résultat dans l'inspecteur web pour un cas correct et pour le cas rencontré avec le bug

![image](https://user-images.githubusercontent.com/18677414/67679308-b471d580-f980-11e9-9b74-f73cfd904e56.png)

![image (1)](https://user-images.githubusercontent.com/18677414/67679316-b6d42f80-f980-11e9-82af-9a511a31e1a4.png)

BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?
Afficher les dates exactes pour les articles retournés par la fonctionnalité de recherche

 - Comment valider ?
Faire une recheche sur le blog et valider que les dates sont valides (pas en `Invalid Date`) et correspondent bien à celles affichées dans les articles complets

CONTEXTE TECHNIQUE
------------------------------------------
Bug rencontré sur Firefox Quantum 68.0 (64-bit) et Debian Buster (`Linux debian 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux`)

Le bug n'est pas rencontré sur Chromium (`Version 73.0.3683.75 (Developer Build) built on Debian buster/sid, running on Debian 10.1 (64-bit)`)

**Comment by guillemcanal** [comment]
@dimitri-fert J'ai trouvé l'erreur Algolia nous revois un format de date qui n'est 
incompatible avec JS: ![oups](https://i.imgur.com/XCQRjWN.png)

Je ne sais pas si ça vient de nous où d'eux, en tout cas, je peu faire facilement un fix.

**Comment by flemzord** [comment]
@dimitri-fert On peut clôturer le bug ?
